### ISSUE TITLE
R66 GG

### ISSUE THREAD

**Issue by mengyanb** [waarp/Waarp#1]
Hello!
I want to know what  R66GG it is(WarrpGateWayFtp or other) and I cant see any Configer for it.Please  give me some advice.

**Comment by mengyanb** [comment]
How to apply the gateway to  between R66 client and R66 server

**Comment by fredericBregier** [comment]
I don't know where you get "R66GG" name.
There is Waarp R66 (old name was Goldengate R66), and Waarp Gateway FTP.
For Waarp R66, see 
- the installation procedure http://waarp.github.io/Waarp/WaarpR66Installation.html

For Waarp Gateway FTP, see:
- some example configuration https://github.com/waarp/WaarpGatewayFtp/tree/master/src/main/example/config
- the API http://waarp.github.com/WaarpGatewayFtp, 
- and the API for the tasks that will allow to link the gateway as a R66 client to the R66 server: http://waarp.github.io/WaarpR66/api/org/waarp/gateway/kernel/exec/package-summary.html
   - http://waarp.github.io/WaarpR66/api/org/waarp/gateway/kernel/exec/AbstractExecutor.html
   - http://waarp.github.io/WaarpR66/api/org/waarp/gateway/kernel/exec/R66PreparedTransferExecutor.html

**Comment by mengyanb** [comment]
Thanks
The transfor is like "R66Client  to  Waarp Gateway FTP to R66Server".So Whether Waarp Gateway FTP is the role of forwarding.And whether the file is landing in gateway.

**Comment by fredericBregier** [comment]
The Waarp Gateway FTP only accept FTP incoming connexion, from any standard FTP client. It then allows to forward the file to a Waarp R66 server (or do anything else).
So a R66 Client cannot connect to a Gateway FTP server, but an FTP client can...

**Comment by mengyanb** [comment]
Thank you for your answer,but i still have some questions.
I get R66GG in http://waarp.github.io/Waarp/WaarpR66.html
Please tell me what it is!

**Comment by waarpcncjh** [comment]
hello When I was learning AllJarsWaarpR66-3.0.4, has launched the service side (server. Bat) and client (R66ClGUI. Bat), can also succeed through the client send the file to the server, but now also don't know how to put the gateway (getway) is applied to the inside, please help me, how in the process of a transfer application gateway, the gateway how to start, how to configure, how to put forward a transfer requests through a gateway to the server

**Comment by waarpcncjh** [comment]
[WaarpGatewayKernel-master.zip  ]This is the gateway R66 code? , how to start his, how to configure his relationship with the client, server

**Comment by fredericBregier** [comment]
R66GG is the old version (more than 3 years old). Waarp R66 from http://waarp.github.io/Waarp/Downloads.html is the new version (in particular http://sourceforge.net/projects/waarp/files/AllJars/AllJarsWaarpR66-3.0.4-Full.zip/download ).
You have to configure the XML file to fit your needs, your database (if any), following this: 
http://waarp.github.io/Waarp/WaarpR66Configuration.html
Then you can go through other web pages from http://waarp.github.io/Waarp/WaarpR66.html

**Comment by waarpcncjh** [comment]
Now have such a situation, I installed the two R66 server, to realize the file transfer between two servers, but I also want to add a gateway between the two servers, the gateway is how?

**Comment by waarpcncjh** [comment]
I don't know how to configure, gateway forwarding rules, please give me an example of a gateway rules!

**Comment by fredericBregier** [comment]
OK I'm closing this one since you have 2 opened issues for the very same subject... ;-)
