### ISSUE TITLE
I kow how to start R66Server and Client ,but I want to start  R66Server as a proxy,but I dont know how to init it.Can you show me  the steps

### ISSUE THREAD

**Issue by mengyanb** [waarp/Waarp#3]

**Comment by mengyanb** [comment]
11:48:45.864 [main] ERROR org.waarp.openr66.proxy.R66Proxy - org.waarp.openr66.proxy.R66Proxy.initialize(R66Proxy.java:71) : Startup of Proxy is in error
io.netty.channel.ChannelException: address already in use by: [id: 0xf28b2a1b, local:0]

this is the erro

**Comment by fredericBregier** [comment]
See #2 since it is the very same issue.
