### ISSUE TITLE
R66Proxy cant startup

### ISSUE THREAD

**Issue by mengyanb** [waarp/Waarp#4]
I use your config to start proxy,but address already in use.

(14:54:54.436 [main] ERROR org.waarp.openr66.proxy.R66Proxy - org.waarp.openr66.proxy.R66Proxy.initialize(R66Proxy.java:71) : Startup of Proxy is in error
io.netty.channel.ChannelException: address already in use by: [id: 0xf88e5056, local:0])

I didnt start another server  and i think  " local:0 " is the reason,i I didn't change the configuration.You can tell me where  is wrong!

**Comment by fredericBregier** [comment]
Opening 2 issues for the very same point is not a good habit...

What is your config file?

**Comment by fredericBregier** [comment]
No more information from 1 month could tend to consider this as closed.
You can of course reopen it if you have more information.
